use alloy::{primitives::Log, sol, sol_types::SolEvent};

macro_rules! try_parse_event {
    ($log:expr, $event_type:ty, $variant:path) => {
        <$event_type>::decode_log($log.as_ref())
            .ok()
            .map(|event| $variant(event.data))
    };
}

sol! {
 #[allow(missing_docs)]
    #[derive(Debug)]
    #[sol(rpc)]
    contract Fourmeme {
        /// TokenPurchase(address,address,uint256,uint256,uint256,uint256,uint256,uint256)
        event TokenPurchase(
            address token,
            address account,
            uint256 price,
            uint256 amount,
            uint256 cost,
            uint256 fee,
            uint256 offers,
            uint256 funds
        );

        /// TokenSale(address,address,uint256,uint256,uint256,uint256,uint256,uint256)
        event TokenSale(
            address token,
            address account,
            uint256 price,
            uint256 amount,
            uint256 cost,
            uint256 fee,
            uint256 offers,
            uint256 funds
        );

        /// TokenCreate(address,address,uint256,string,string,uint256,uint256,uint256)
        event TokenCreate(
            address creator,
            address token,
            uint256 requestId,
            string name,
            string symbol,
            uint256 totalSupply,
            uint256 launchTime,
            uint256 launchFee
        );

        /// LiquidityAdded(address,uint256,address,uint256)
        event LiquidityAdded(
            address base,
            uint256 offers,
            address quote,
            uint256 funds
        );
    }
}

// Re-export the event types generated by the sol! macro
pub use Fourmeme::*;

#[derive(Debug, Clone)]
pub enum FourmemeEvent {
    TokenPurchase(TokenPurchase),
    TokenSale(TokenSale),
    TokenCreate(TokenCreate),
    LiquidityAdded(LiquidityAdded),
}

#[inline]
pub fn parse_fourmeme_event_by_topic(log: &Log) -> Option<FourmemeEvent> {
    try_parse_event!(log, TokenPurchase, FourmemeEvent::TokenPurchase)
        .or_else(|| try_parse_event!(log, TokenSale, FourmemeEvent::TokenSale))
        .or_else(|| try_parse_event!(log, TokenCreate, FourmemeEvent::TokenCreate))
        .or_else(|| try_parse_event!(log, LiquidityAdded, FourmemeEvent::LiquidityAdded))
}
